# Generated by Django 4.0.8 on 2024-09-12 22:02

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import urls.models
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, validators=[utils.validators.validate_not_naive])),
                ('updated_at', models.DateTimeField(auto_now=True, validators=[utils.validators.validate_not_naive])),
                ('url', models.URLField(blank=True, max_length=255, null=True, validators=[utils.validators.is_https])),
                ('token', models.CharField(editable=False, max_length=5)),
                ('expiration_date', models.DateTimeField(default=urls.models.get_default_expiration_date)),
            ],
        ),
        migrations.CreateModel(
            name='UrlUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_users', to='urls.url')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='UrlUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, validators=[utils.validators.validate_not_naive])),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='urls.url')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(condition=models.Q(('url', 'https://shayestehhs.com')), fields=['url'], name='ready_to_set_token_urls'),
        ),
        migrations.AddIndex(
            model_name='url',
            index=django.contrib.postgres.indexes.HashIndex(fields=['token'], name='urls_url_token_44aa35_hash'),
        ),
    ]
