# Generated by Django 5.0.8 on 2024-09-21 08:04

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0005_url_user_delete_urluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True, validators=[utils.validators.is_https]),
        ),
    ]
