# Generated by Django 5.0.8 on 2024-09-21 10:06

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0006_alter_url_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='new_url',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True, validators=[utils.validators.is_https]),
        ),
    ]
