# Generated by Django 5.0.8 on 2024-09-21 10:10

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0007_url_new_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='new_url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[utils.validators.is_https]),
        ),
    ]
